### ISSUE TITLE
Portaria 1631 de 2015 --> MS recomenda quantitativos de profissionais

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/dataLab#11]

**Comment by camilaccolares** [comment]
[Parametros_SUS_2015.pdf](https://github.com/EscolaDeSaudePublica/dataLab/files/4232590/Parametros_SUS_2015.pdf)

**Comment by marameida** [comment]
Documento registrado em card #76, conforme alinhado com @camilaccolares.
