### ISSUE TITLE
Portaria 2979 de 11/2019 --> define o novo financiamento da APS.

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/dataLab#12]

**Comment by camilaccolares** [comment]
[novo-financiamento-APS-previne-brasil-oficina.pdf.pdf](https://github.com/EscolaDeSaudePublica/dataLab/files/4232585/novo-financiamento-APS-previne-brasil-oficina.pdf.pdf)

**Comment by camilaccolares** [comment]
[novo-financiamento-APS-previne-brasil-oficina.pdf](https://github.com/EscolaDeSaudePublica/dataLab/files/4232587/novo-financiamento-APS-previne-brasil-oficina.pdf)

**Comment by camilaccolares** [comment]
[portaria2979.pdf](https://github.com/EscolaDeSaudePublica/dataLab/files/4232609/portaria2979.pdf)

**Comment by aislansf** [comment]
@uira o card não apresenta informações suficientes para realizar atividade.

**Comment by marameida** [comment]
Documento registrado em card #76, conforme alinhado com @camilaccolares.
