### ISSUE TITLE
Realizar o cruzamento do provimento com os indicadores epidemiológicos.

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/dataLab#16]

**Comment by aislansf** [comment]
@uira essa demanda é a mesma que o [integrasus](https://integrasus.saude.ce.gov.br/#/indicadores/indicadores-coronavirus/coronavirus-ceara) faz ?

**Comment by marameida** [comment]
@aislansf  sugiro confirmar com o CISEC se essa demanda já não foi realizada.

**Comment by aislansf** [comment]
Essa demanda já está contemplada nos épicos que estamos desenvolvendo com a própria base do projeto mapa.
