### ISSUE TITLE
Painel de Médicos - Exibir delta considerando as metas do MS.

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/dataLab#22]

**Comment by camilaccolares** [comment]
![foto_quadro_dr_marcelo](https://user-images.githubusercontent.com/58710064/75366830-1e05e000-589e-11ea-9439-b242318e34a7.jpg)

**Comment by uira** [comment]
https://github.com/EscolaDeSaudePublica/dataLab/issues/11

**Comment by aislansf** [comment]
@uira esse card não é o mesmo da força de trabalho ?

**Comment by marameida** [comment]
Alinhado com @camilaccolares que essa atividade se refere ao Dimensionamento da Força de Trabalho. Ver issue #76.
