### ISSUE TITLE
Campos adicionais da API do IntegraSUS

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/dataLab#28]
Gravar no banco do metabase os campos "obitoConfirmado" e "dataObito" provenientes da API do IntegraSUS.

**Comment by aislansf** [comment]
@victorMagalhaesPacheco qual o contexto desse card ?

**Comment by uira** [comment]
Isso perdeu o sentido, inclusive foi para um repositório próprio. Fechando por motivos de já foi.
