### ISSUE TITLE
[ MAPA ] Dashboard Força de Trabalho

### ISSUE THREAD

**Issue by aislansf** [EscolaDeSaudePublica/dataLab#33]
Material de referência: https://docs.google.com/document/d/1mVUm-M_T4lP0a46IrVesbD42fVwbBmXdUCbIX_i-NbY/edit?usp=sharing

- [x] Download e carga da base de dados do CNES
- [x] Download e carga da base de dados do CBO
- [x] Download e carga da base de dados populacionais (IBGE)
- [x] Corrigir termos duplicados da tabela CBO
- [x] Estratificação dos CBOs no banco
- [x] Verificar grafia dos municípios no metabase e na base do mapa
- [x] Criação dos indicadores no Metabase - 1
- [x] Criação dos indicadores no Metabase - 2
- [x] Criação dos indicadores no Metabase - 3
- [x] Atualizar indicadores com os dados do mapa em produção
- [x] Disponibilização do dashboard no Mapa
- [x] Criar uma tabela para controle de atualizações dos dados (id_atualizacao, timestamp)
- [x] Adicionar FK na tabela cnes relacionando-a com a tabela atualizacoes

**Comment by aislansf** [comment]
Criei um script para converter a base dbc para csv utilizando a ferramenta R Studio, segue o script.

# Acessando diretório do arquivo DBC
setwd("~/Downloads/arquivo")

# Instalando pacote de leitura de arquivos DBC
install.packages("read.dbc")

# Chamando a biblioteca para uso
library(read.dbc)

# Adicionando uma nova variável carregada com o arquivo DBC
novo<-read.dbc("PFCE2110.dbc")

# Exibindo os dados 
head(novo)

# Exportando os dados para CSV
write.csv(novo,file ="PFCE2110.csv")

**Comment by aislansf** [comment]
Na atividade dos dados populacionais selecionar os dados mais atualizados e organizados por município

**Comment by camilaccolares** [comment]
[LOCORREGIONALIZAÇÃO - PORTARIA 254, DE 25 DE AGOSTO DE 2020 DOU 374 - EDIÇÃO 165.xls](https://github.com/EscolaDeSaudePublica/dataLab/files/7598288/LOCORREGIONALIZACAO.-.PORTARIA.254.DE.25.DE.AGOSTO.DE.2020.DOU.374.-.EDICAO.165.xls)

**Comment by aislansf** [comment]
Dashboard mapa http://metabase.esp.ce.gov.br/public/dashboard/3ddb5bd9-6fce-422b-934c-b9e6241b3342

**Comment by aislansf** [comment]
Tendo em vista que cosneguimos avançar com as informações que nos foram disponibilizadas já concluímos 11 atividades das 13. Então, a @camilaccolares vai entrar em contato com um time interno da ESP (CEATS) para conseguir as informações para finalizar as outras atividades. Até lá estamos com esse card nos impedimentos.

**Comment by aislansf** [comment]
@marameida esse é o card que o @uira comentou no telegram

**Comment by marameida** [comment]
Feita solicitação por email para Educação Permanente quanto ao levantamento sobre todas as profissões de saúde, de índices indicados pelas recomendações internacionais (OMS e OPS) e nacionais (SUS).

**Comment by marameida** [comment]
Reforçada a importância dessas referências. Solicitado abrir uma estória pra analisar esse documento e elencar gráficos, com análises que possam ser replicadas no mapa da saúde.

**Comment by uira** [comment]
@marameida

**Comment by marameida** [comment]
Encaminhada resposta por email da Educação Permanente. A mesma referiu não ter essas informações compiladas e pela demanda do serviço sua equipe não poderá fazer esse levantamento no momento. Sugeriu algumas referências por categoria. @uira @aislansf

**Comment by uira** [comment]
@marameida Beleza. Vamos então avançar pra liberar o dashboard pra produção. 

Precisamos marcar uma reunião para apresentação e aprovação, com o Cisec e a Diretoria de Educação.  Por favor, Samara Mesquita , pode falar com a Flavianne, para agendar

**Comment by marameida** [comment]
Ok, ciente.

**Comment by marameida** [comment]
Análise de referência:
https://drive.google.com/file/d/1dYZMpH0-ZlEg_s4bTvd0ZvfeLjVbl7Ln/view?usp=sharing

**Comment by marameida** [comment]
Reunião solicitada por intermédio da Flaviane (por telegram e email). No aguardo por disponibilidade e retorno.

**Comment by marameida** [comment]
**Reunião com Dra Alice e equipe para validação interna (11/03):**

**Sugestões levantadas:**
- Discussão sobre estratégias para auxiliar no processo de atualização dos dados do CNES;
- Sobre as categorias inicialmente avaliadas, serão mantidas somente essas?;
- Para os profissionais cadastrados em mais de um local: duplicidade?
- Detalhamento das profissões (especialidades médicas?)
- Verificar sobre dados dos residentes (locais e gaps de atuação);

**Encaminhamentos:**
- [x ] Incluir a fonte dos dados no dashboard (Fonte: CNES)
- [x ] Elaborar apresentação resumo
- [x ] Validar MVP com Setor de Educação e CISEC

**Comment by marameida** [comment]
No aguardo por melhor direcionamento junto ao CISEC, conforme devolutiva da gestão.

**Comment by marameida** [comment]
@JesseOliveiraUFC irá sugerir disponibilização do dashboard no Mapa.

**Comment by marameida** [comment]
No momento a disponibilização do dashboard ficará no aguardo pelos encaminhamentos  resultantes da inception. Orientação da equipe do Mapas.

**Comment by aislansf** [comment]
@uira entramos em contato com o CISEC sobre as contribuições que poderíamos realizar entre DATALAB  e CISEC. Ficamos com o direcionamento de fortalecer os esforços no cenário ideal dos profissionais da força de trabalho. Para encerrarmos esse card sobre o que nós já desenvolvemos precisamos da validação final do Dr. Marcelo, porém, em uma conversa com a Flaviane e a Dra. Alice é que nesse momento o Dr. Marcelo não irá priorizar essa demanda. @uira  podemos finalizar esse card ou ele será mantido nos impedimentos para sempre ?

**Comment by uira** [comment]
@aislansf Essa atividade não é do Marcelo, e sim do projeto Mapa da Saúde, prevista na EAP e nas entregas e resultados esperados. Logo, deve ser finalizada e é prioritária. 

Ela deve ser finalizada COM URGENCIA, configurando para puxar os dados à partir do Mapa da Saúde, pra que seja um board em tempo real dos dados do Mapa.

Depois de concluido, deve ser incluída no painel de indicadores do Mapa da Saúde. @victormagpac

**Comment by aislansf** [comment]
Alinhando com o @victorMagalhaesPacheco vimos a necessidade de priorizarmos no mapa a inclusão do cadastro do CNS do profissional, tendo em vista que atualmente pode existir a duplicidade dos dados. Por exemplo o Dr. Marcelo fez seu cadastro no mapa e possui cadastro na base do CNES, quando ocorro a atualização dos dados do que CNES no mapa é resgatado essas informações do Dr. Marcelo, gerando duplicidade no mapa. Atualmente não existe nenhuma outra característica além do CNS que pode cruzar os dados do mapa com os dados do CNES.

**Comment by JesseOliveiraUFC** [comment]
Atualização dos indicadores com os dados do Mapas em Produção realizada com sucesso.
A dashboard atualizada pode ser acessada nesse link:
-> https://metabase.esp.ce.gov.br/public/dashboard/34161172-bcdc-4f6d-a939-6543e4e752ee

**Comment by JesseOliveiraUFC** [comment]
Inseridos FIltros de pesquisa dentro da Dashboard acima.
Filtros:
[x] por região de saúde.
[x] por área de saúde.

**Comment by JesseOliveiraUFC** [comment]
Dashboard com os indicadores da força de trabalho baseada nos dados provenientes do Mapa da Saúde foi implementada com SUCESSO. Em alinhamento com @victorMagalhaesPacheco, ficou decidido que aguardaremos as novas definições provenientes da planning acerca da forma de disponiblização da dashbord dentro do Mapa da Saúde.
Aguardando novas diretrizes para verificar se esse Card é encerrado ou não.

**Comment by marameida** [comment]
Ciente. Demandas atendidas.

**Comment by marameida** [comment]
Próximas definições serão registradas em cards futuros.
