### ISSUE TITLE
Painel de Informações dos Chamados da ESP - Todos os dados, de todos os chamados, e mais detalhado das demandas de Sistemas

### ISSUE THREAD

**Issue by aislansf** [EscolaDeSaudePublica/dataLab#39]
- [x] Obter as credenciais de acesso à base do sistema de chamado
- [x] Instalar e configurar banco de dados MySQL
- [x] Criar o banco do sistema de chamado
- [x] Gerar modelo de dados do sistema de chamado
- [x] Estruturar o relacionamento das tabelas
- [x] Criar banco do sistema de chamado no DW
- [x] Criar estrutura de ETL para conectar com o DW do datalab
- [x] Adicionar banco do sistema de chamdo do DW no metabase
- [x] Adicionar indicadores no painel do metabase na base do sistema de chamado

**Comment by aislansf** [comment]
Agendando reunião com o Rafael para entender melhor essa demanda.

**Comment by aislansf** [comment]
Conversa com o Rafa sobre o gerenciamento de chamadas de atendimento.

- Apresentação do sistema OTRS (Central de suporte)
- Limitações do OTRS em relação a geração de gráficos.
- Identificar quem gerencia o banco de dados do sistema OTRS
- Providenciar modelo de dados do OTRS
- Utilizar essa planilha como base para construção da dashboard no metabase
https://docs.google.com/spreadsheets/d/1KIS1lu7uCFfaYmGWMw0rlzoS7SbiLZuk3OqUAxxGyQs/edit?usp=sharing

**Comment by aislansf** [comment]
Aguardando informações do @rmadev-master  de acesso ao banco do SISTEMA OTRS

**Comment by aislansf** [comment]
Utilizar credenciais de acesso

Link do sistema:
https://centraldesuporte.esp.ce.gov.br/otrs/customer.pl?Action=CustomerTicketMessage

**Comment by aislansf** [comment]
![otrs](https://user-images.githubusercontent.com/59830577/157778527-48bf0abf-78d8-45c1-ad42-f5d6b7fe0f18.jpg)

**Comment by aislansf** [comment]
Vou precisar construir um material investigativo das tabelas do sistema OTRS para identificar os relacionamentos entre elas, pois, as tabelas não possuem relacionamento com chave estrageiras (FK), isso impossibilita gerar uma visualização com esses relacionamentos. Analisando o sistema esse relacionamento entre as tabelas é feito no back-end do sistema. O foco é identificar as tabelas que respondem as perguntas iniciais do @rmadev-master.

**Comment by aislansf** [comment]
![mapeamento_otrs](https://user-images.githubusercontent.com/59830577/157948155-054c0955-9f17-49d2-90dc-ab4c19d9f7a1.JPG)

**Comment by aislansf** [comment]
O produto JURÍDICO não contém dentro da base do sistema de chamados na coluna serviços...

**Comment by marameida** [comment]
Agendada reunião para validação de dashboard com @rmadev-master.
Data: 23/03
Horário: 14h

**Comment by aislansf** [comment]
Dashboard:
https://metabase.esp.ce.gov.br/public/dashboard/0950a630-b91a-48be-be7a-fd5338880182

As informações do banco do sistema de chamado devem ser atualizadas a cada 1hrs seguindo a necessidade do @rmadev-master.

**Comment by aislansf** [comment]
Apresentação: 
https://docs.google.com/presentation/d/1TmY8kOb5ij7BcFyZk6_Uu3EOOOeQZygBK2piOsd-Ln4/edit#slide=id.g11e2fe2850d_0_47

Documentação para segunda versão do dashboard:
https://docs.google.com/document/d/1ggbVmOmrdNQCxwlutLWKu9Jcbh5Sc8_v-ks8_OlWMUw/edit

Recursos para a dashboard da segunda versão.
- Quantos chamados por setor solicitante
- Adicionar filtro por solicitante, setor, serviços, produtos e nível de prioridade
- Ranking de chamados por atendentes
- Identificar a possibilidade da categorização das respotas mais frequentes dos chamados

**Comment by aislansf** [comment]
@elpadrejorge você consegue dar um tapa no visual desse dashboard?

**Comment by pauloamoreira** [comment]
.caro @aislansf precisamos ter mais clareza sobre o escopo a ser cumprido pelo DesignLab. sugiro que você aperfeiçoe o escopo da tarefa seguindo o modelo do template. em alguns casos, vale a pena inserir campos com demandas específicas, como por exemplo: "Escopo DEV" e "Escopo DesignLab", para estabelecer de forma clara o que cada time irá entregar.

**Comment by aislansf** [comment]
@pauloamoreira entendo a necessidade do ajuste do card para o modelo de estória do usuário, porém esse card é antigo e basicamente a necessidade do @rmadev-master é ter a visão do time do designlab sobre esse [dashboard](https://metabase.esp.ce.gov.br/public/dashboard/0950a630-b91a-48be-be7a-fd5338880182) se as cores estão no padrão adequado, se os gráficos representam bem as informações dispostas e se está de fácil entendimento. Caso tenha alguma dúvida podemos ir alinhando a demanda.

**Comment by marameida** [comment]
@JesseOliveiraUFC pode agilizar essa questão com a equipe do design?

**Comment by RaniGub** [comment]
Boa tarde @aislansf, para visualizarmos oportunidades de melhoria visual no esquema gráfico é necessário compreender do que se trata com clareza. Estamos fora do contexto de evolução da tarefa e ela não possui história nem escopo claramente definido para dar dicas de compreensão para quem não é da área. É preciso que você dedique um tempo para conversar com o @pauloamoreira ou @elpadrejorge para que a tarefa fique clara e possamos colocar em nosso planejamento semanal de atividades.

**Comment by aislansf** [comment]
@RaniGub já foi resolvido internamente essa demanda e para as próximas demandas que surgirão iremos requisitar do stakeholder a estória completa da issue. Agradecido pela disponibilidade e atenção do time do Design lab para sempre.
