### ISSUE TITLE
Criar dashboard do RPES para o DW no ambiente de produção

### ISSUE THREAD

**Issue by aislansf** [EscolaDeSaudePublica/dataLab#40]
Atualmente o RPES utiliza o ambiente de homologação para representar os dados no dashboard criado no metabase. É importante migrar a estrutura para o ambiente de produção.

- [x] Criar banco de dados do RPES no DW
- [x] Criar uma cópia da base do RPES
- [x] Importar cópia da base no DW
- [x] Criar conexão da base RPES do DW no metabase de produção
- [x] Criar painel de dashboard do RPES no metabase de produção
- [x] Copiar todas as perguntas do dashboard de homologação para ambiente de produção do metabase

**Comment by aislansf** [comment]
@marameida mais um card sobre o RPES

**Comment by aislansf** [comment]
Novo link do dashboard do RPES no ambiente em produção...
Foi realizado uma nova carga dos dados para manter as informações na dashboard atualizadas

http://metabase.esp.ce.gov.br/public/dashboard/f70e2d8d-0355-481c-a3aa-a78980ebd9b7

**Comment by uira** [comment]
@aislansf Carga de dados?

Não temos uma conexão direta?
