### ISSUE TITLE
Coletar dados dos responsáveis dos produtos da ESP para identificar o uso de dashboard em seus produtos

### ISSUE THREAD

**Issue by aislansf** [EscolaDeSaudePublica/dataLab#41]

**Comment by marameida** [comment]
Formulário enviado para gestores de produtos (email e telegram):
iSUS - Laysa 
Mapa da Saúde - Thais 
QualiQuiz - Ana Bruna 
ID Saúde - Victor 
SAGU - Victor 
RPES - Samara 
Portal Coronavírus - Washington 
Elmo - Clarissa 
Central do SUS - Daniel

No aguardo por retorno das informações.

**Comment by marameida** [comment]
Formulário aplicado. Planilha de respostas.
https://docs.google.com/spreadsheets/d/10l4DO6Ww1G6BhsdXYD2UTwVZBK1P3LQ5RABEwBJEZMA/edit#gid=305718107
