### ISSUE TITLE
Implementar ficha avaliativa pré e pós implantação de dashbards

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/dataLab#44]
**Eu como**equipe DATALAB
**Quero** elaborar ficha avaliativa
**Para que** possa ser aplicada nos momentos pré e pós implantação de dashboards.

# Contexto
## O que originou
A ficha avaliativa permitirá um retorno comparativo nos momentos antes e após implantação dos painéis de indicadores demandados.
 
## Qual solução proposta
- [x ]  Pesquisa Bibliográfica para modelos existentes
- [x ] Adaptação dos instrumentos para realidade local
- [x] Incluir formulários no mapas

# Critérios de aceitação

- [x] **Dado que** após elaboração das fichas
**Quando** os dashboards forem solicitados pelos produtos/projetos
**Então**os instrumentos serão aplicados antes e após implementação.

## Observações
- Tomada de decisão sobre os dados
- Valor/importância 
- Experiência do usuário sobre dashboard
- Frequência de uso

Quais perguntas podemos fazer que respondam esses pontos?

**Comment by marameida** [comment]
Elaboração de ficha pós implementação (em refinamento):
https://docs.google.com/document/d/1PjrnH01zXLcAofqdf7QfmhYIX9eGqfQICj2c94BWnq8/edit

**Comment by JesseOliveiraUFC** [comment]
Elaborada uma sugestão de questão relacionada a quais condições de trabalho melhoraram após o uso da Dashboard em diferentes tópicos (questão 13) [aberta a sugesstões].

**Comment by marameida** [comment]
Questionário comparativo em elaboração:
https://docs.google.com/document/d/1ngsG0NYecWYQKA25M3mFjzk6Qxgx6yexv5yShnoASG0/edit

**Comment by JesseOliveiraUFC** [comment]
Elaboradas duas novas perguntas acerca da usabilidade e interesse dos gestores na dashboard.

**Comment by marameida** [comment]
Instrumentos validados por equipe DATALAB. Ver possibilidade de inclusão no Mapas:

FORMULÁRIO DE AVALIAÇÃO PARA USABILIDADE
DE DASHBOARD- DATALAB:
https://docs.google.com/document/d/1ngsG0NYecWYQKA25M3mFjzk6Qxgx6yexv5yShnoASG0/edit
FORMULÁRIO DE AVALIAÇÃO COMPARATIVA: https://docs.google.com/document/d/1PjrnH01zXLcAofqdf7QfmhYIX9eGqfQICj2c94BWnq8/edit

**Comment by aislansf** [comment]
Passo a passo para criar uma oportunidade no MAPA.

Faz login > meu perfil > meu projetos > adicionar novo projeto > preencha os dados > completar edição agora > aba oportunidades > criar oportunidade > avaliação simplificada > preenche os dados e adiciona os campos do formulário > clica no botão salva (publicar) > feito!

**Comment by marameida** [comment]
Iniciado processo de inclusão de formulários no Mapas.
https://mapa.sus.ce.gov.br/oportunidades/edita/244/
-[x] Formulário Pré Implementação

**Comment by marameida** [comment]
Incluídos os três formulários avaliativos no mapas:
https://mapa.sus.ce.gov.br/oportunidades/edita/258/
- [x] Formulário Pré Implementação
- [x] Formulário Pós Implementação
- [x] Formulário de Usabilidade
