### ISSUE TITLE
Integrar DATALAB com REDMINE

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/dataLab#50]

**Comment by aislansf** [comment]
Tutorial do redmine
https://docs.google.com/document/d/1bFr0sVJpDCph16_53s8E5zKZEmX1ECVDiperKxBVDSM/edit

**Comment by marameida** [comment]
Processo iniciado. Criado usuários da equipe juntamente com @rmadev-master. No aguardo por treinamento complementar, comentado pelo time de Projetos, para que seja possível melhor reconhecimento das funções.
