### ISSUE TITLE
Dashboard Sistema de chamados - 2ª Versão

### ISSUE THREAD

**Issue by aislansf** [EscolaDeSaudePublica/dataLab#68]
**1ª Versão do dashboard:**  
https://metabase.esp.ce.gov.br/public/dashboard/0950a630-b91a-48be-be7a-fd5338880182

Rercusos para a **2ª versão** do dashboard

- [x] Adicionar gráfico que contabilize o quantitativo dos chamados por setor solicitante
- [x] Adicionar filtro por solicitante, setor, serviços, produtos e nível de prioridade
- [x] Ranking de chamados por atendentes
- [x] Identificar a possibilidade da categorização das respotas mais frequentes dos chamados

**Comment by aislansf** [comment]
@rmadev-master aguardando validação das novas features adicionadas

**Comment by aislansf** [comment]
Obs: Os filtros de serviços e solicitante não foram adicionados devido ao metabase não reconhecer caracteres especiais como uma categoria.
No caso dos serviços por conta do :: 
No caso dos solicitantes por conta do .

**Comment by rafaelmassuncao** [comment]
> @rmadev-master aguardando validação das novas features adicionadas

Não encontrei problemas no modelo do Dashboard construído. Aprovado. Para entrar em produção, por favor, atualizar os chamados para a data atual. 

@aislansf, qual a possibilidade de haver atualização de dados em tempo real?

**Comment by aislansf** [comment]
@rmadev-master estamos trabalhando com o @fwandson para disponibilizar um ambiente para tornar essa automação em tempo real.
