### ISSUE TITLE
Dashboard do qualiquiz - 2ª versão

### ISSUE THREAD

**Issue by aislansf** [EscolaDeSaudePublica/dataLab#69]
**1ª versão do dashboard:** 
https://metabase.esp.ce.gov.br/public/dashboard/5625fd38-bd17-4638-8545-993adfb01824

Encaminhamentos da reunião com Dr Batista para a **2ª versão do dashboard** do qualiquiz
- [x] Listar as perguntas passando com o mouse.
- [x] Colocar período (filtro por período)
- [x] Adicionar gráfico para mensurar volume de respostas ao longo do tempo
- [x] Adicionar gráfico que informe volume de acesso.
- [x] Desenvolver ETL para atualização do dashboard
- [x] Disponibilizar dashboard atualizado

**Comment by aislansf** [comment]
A atividade gerar planilha/relatório dos dados deve ser colada em uma issue separada, atualmente para baixar os arquivos do resultado da pesquisa deve-se disponibilizar um acesso ao metabase e essa liberação pode ocasionar um problema caso o usuário altere algum script do banco. Neste caso, é importante analisar outra estratégia para gerar o relatório dos dados.

**Comment by aislansf** [comment]
Finalizei a estrutura do ETL para aplicação do Qualiquiz, respondendo as peguntas feitas pelo Dr. Batista e a Natana.

[https://app.zenhub.com/files/240087549/d66a3008-7143-476e-8cb5-62322494ec49/download](https://app.zenhub.com/files/240087549/d66a3008-7143-476e-8cb5-62322494ec49/download)

**Comment by aislansf** [comment]
Link da versão atualizada do dashboard da versão 2:
https://metabase.esp.ce.gov.br/public/dashboard/5625fd38-bd17-4638-8545-993adfb01824

**Comment by JesseOliveiraUFC** [comment]
Seria interessante na 2a versão do dashboard que na aba de tempo médio de resposta tivesse a unidade, pois não ficou claro se é em minutos ou não.

**Comment by aislansf** [comment]
@JesseOliveiraUFC bem observado! Vou adicionar o termo minutos

**Comment by aislansf** [comment]
Dashboard disponibilizado para validação e a atividade de gerar relatório dos dados precisa realizar um estudo para identificar a melhor forma de disponibilizar os dados já que no metabase não é possível por link público.

**Comment by marameida** [comment]
Atividade concluída com validação da Natana e Dr Batista.

**Comment by uira** [comment]
@marameida Favor enviar o link do dashboard para o Grupão, solicitando testes, feedback e divulgação do time de narrativas/ Ascom

**Comment by aislansf** [comment]
@uira Dr. Batista e a Natana deseja uma planilha com os dados do dashboard do qualiquiz, porém, no metabase só é possível compartilhar de forma pública os gráficos da dashboard para gerar um relatório desses dados não é possível pelo metabase. O Dr. Batista e a Natana deseja aplicar um filtro ver os gráficos da dashboard e fazer um download do resultado do filtro em uma planilha para realizar análises estatísticas ou afins da pesquisa. Esse é o contexto do item sobre baixar relatório no metabase.

**Comment by marameida** [comment]
@uira vamos confirmar com a Natana sobre essa divulgação do link ou se é interesse do setor manter esses dados somente para acompanhamento interno.

**Comment by marameida** [comment]
Novas demandas de ajustes solicitadas. Serão encaminhadas para 3ª versão.

**Comment by uira** [comment]
@marameida Essa avaliação já foi feita por mim. Por favor, siga com a atividade da divulgação.

**Comment by marameida** [comment]
Certo. Feito. Divulgado e sugerido o mesmo para equipe da DIDES (Natana).
