### ISSUE TITLE
Integração da Dashboard da Força de Trabalho no Mapa da Saúde

### ISSUE THREAD

**Issue by JesseOliveiraUFC** [EscolaDeSaudePublica/dataLab#85]
# Objetivo

*Eu como* DataLab
*Quero* solicitar ao DesignLab as definições de aparência da Dashboard
*Para que* seja implementada e exibida no Mapa da Saúde.

# Contexto
## Qual solução proposta
- [x] Definir onde a dashboard será exibida dentro do Mapa da Saúde.
- [x] Definir se a dashboard será inserida no backend do Mapa ou se será fornecido acesso ao link externo da dashboard.
- [x] Definir a forma de apresentação da dashboard. Temos 2 opções:
--- Mostrar a dashboard por completo com todas as categorias profissionais juntas.
--- "Quebrar" a dashboard atual em várias dashboards, uma para cada categoria profissional.

# Fora de Contexto
A dashboard analisa somente 5 categorias profissionais (médicos, enfermeiros, farmacêuticos, fisioterapêutas e Agentes de Saúde). Algumas perguntas podem surgir:
--- Porque somente essas 5? 
--- Quais foram os critérios de escolha? 
--- Por que não analisar os odontólogos, por exemplo? 
--- Seria interessante exibir dados acerca das 14 categorias profissionais da Saúde no Ceará?

# Critérios de aceitação

*Dado que* uma vez definidas todos esses detalhes  
*Quando* recebermos todas as definições de design 
*Então* a dashboard poderá ser implementada dentro do Mapa da Saúde.

# Observações
Colocar essa demanda em caráter de URGÊNCIA, pois as atividades posteriores dependem dessa definição.

**Comment by RaniGub** [comment]
Bom dia @JesseOliveiraUFC , se eu reescrever a história como a sugestão a seguir, faz sentido?

Eu como gestor da ESP
Quero visualizar os indicadores da Força de Trabalho
Para que possam apoiar minha tomada de decisão

**Comment by JesseOliveiraUFC** [comment]
Faz total sentido. Pois eu creio que esse seja um dos principais objetivos com a dashboard.

**Comment by JesseOliveiraUFC** [comment]
Pensando bem, @RaniGub, essa demanda não tem nada a ver com os gestores da ESP, ainda. Pois só queremos ter uma definição de como vamos implementar a dashboard dentro do Mapa da Saúde, inicialmente. 
Pode ser que enxergar o contexto como um gestor auxilie no processo de design, mas o que queremos agora é somente a definição prática da implementação, se vai ser uma dashboard completa, ou se vai quebrar a dashboard em várias, de acordo com a categoria profissional.

Sobre a experiência do usuário, seria mais interessante implementar a dashboard dentro do Mapa ou só fornecer aceso ao link externo seria melhor?

Fico no aguardo das definições.

**Comment by JesseOliveiraUFC** [comment]
Segue o link de acesso à dashboard https://metabase.esp.ce.gov.br/public/dashboard/34161172-bcdc-4f6d-a939-6543e4e752ee

**Comment by RaniGub** [comment]
Observações
 - Verificar a quebra das informações quando o filtro de município é selecionado;
 - O filtro de município não mostra o município abaixo do campo de pesquisa. Corrigir.

MVP 1
- Colocar o filtro de munício como primeiro, considerando ser o que representa maior valor;
- Modificar para: Município, Macrorregião e Microrregião
- Colocar logo do Mapa da Saúde

MVP 2
- Adicionar filtro de Categorias Profissionais;
- Verificar a possibilidade de interrelação entre os filtros.

**Comment by RaniGub** [comment]
https://www.figma.com/file/QZ4BzFVfx9Hn0rrJ077Dkk/Indicadores-da-For%C3%A7a-de-Trabalho

**Comment by RaniGub** [comment]
@JesseOliveiraUFC as informações estarão disponíveis inicialmente somente para admins. Na sprint que ela for ser disponibilizada posso sentar com você para indicar como ela vai aparecer para essas pessoas.

**Comment by JesseOliveiraUFC** [comment]
Problema com o filtro de município resolvido. Agora funciona normalmente e está completamente vinculado aos filtros de macro e microrregião.

MVP 1 
- [x] Colocar o filtro de munício como primeiro, considerando ser o que representa maior valor.
- [x] Modificar para: Município, Macrorregião e Microrregião

**Comment by JesseOliveiraUFC** [comment]
A Atividade proposta neste card já foi concluída com sucesso. O mesmo será fechado.
