### ISSUE TITLE
Escrita de um artigo científico com a descrição da força de trabalho na área da saúde do estado do Ceará

### ISSUE THREAD

**Issue by nestorufpe** [EscolaDeSaudePublica/dataLab#88]
## **Contexto**

-Escrita de um artigo científico com a descrição da força de trabalho na área da saúde do estado do Ceará. O artigo tem por objetivo analisar os dados de profissionais do Mapa da Saúde e realizar a comparação com os indicadores da OMS e Censo 2022. 

## **Critérios de Aceitação**

- [ ] Escrita e publicação do artigo na Revista Cadernos ESP/CE

## Observações
Links de apoio e informações adicionais

**Comment by JesseOliveiraUFC** [comment]
Referenciando alguns documentos como base para a escrita do artigo:

* Documento onde organizamos as nossas referências:
-- https://docs.google.com/spreadsheets/d/1s9TIDc75nA9G0G-TGggoU40WN1MY5dWYofj6MTz40rM/edit#gid=0

* Materiais de referência para a Revisão Sistemática Literária (RSL):
-- https://app.zenhub.com/files/240087549/9e68937a-ad2e-4576-861f-2217a624fcd9/download
-- https://app.zenhub.com/files/240087549/c03a5b1b-9844-45d3-8483-01c03548d1aa/download
-- https://app.zenhub.com/files/240087549/88ca3189-3344-434d-b28e-741f816a755b/download

* Textos bases para as definições dos parâmetros a serem analisados (portarias, decretos, etc.):
-- https://app.zenhub.com/files/240087549/41834adf-5021-466e-9d45-a58995a75561/download
-- https://app.zenhub.com/files/240087549/16cb378b-0498-48c8-999f-b1609265d765/download
-- https://app.zenhub.com/files/240087549/8eac6246-5891-40ff-94c0-af709af79586/download

* Os arquivos/textos de referência estão sendo armazenados em uma pasta do Google Drive:
-- https://drive.google.com/drive/folders/1kgbd34abiYsEWH9roZRKMdqBAIxt9HeQ

* Documento que fundamenta a demanda da escrita do artigo:
-- https://docs.google.com/document/d/1mVUm-M_T4lP0a46IrVesbD42fVwbBmXdUCbIX_i-NbY/edit?usp=sharing

**Comment by JesseOliveiraUFC** [comment]
Segue material de referência para cálculo de índices ideais para Agentes Comunitários de Saúde.

https://site.mppr.mp.br/pagina-35.html#:~:text=O%20n%C3%BAmero%20de%20agentes%20comunit%C3%A1rios,UBS%20para%20cada%2012.000habitantes.

**Comment by JesseOliveiraUFC** [comment]
Atualização de progresso da escrita do artigo.

- [x] Inserção de gráficos de indicadores no artigo. 
- [x] Avanço na escrita da seção de Resultados.

O artigo encontra-se com aproximadamente 35-40% da escrta básica concluída.

Segue o documento base para eventuais consultas.

[https://app.zenhub.com/files/240087549/d681f2d0-a232-4848-aeb3-9d5e204b3fa5/download](https://app.zenhub.com/files/240087549/d681f2d0-a232-4848-aeb3-9d5e204b3fa5/download)

Quaisquer sugestões ou críticas são completamente bem-vindas.

**Comment by JesseOliveiraUFC** [comment]
Progresso atual da escrita do artigo.
No contexto da análise dos dados dos profissionais de saúde nas macrorregiões se tornou necessário o desenvolvimento da visualização dos dados em um mapa macrorregionalizado. O processo de construção desse tipo de visualização personalizada seguiu após alinhamento com @victorMagalhaesPacheco onde ele indicou e repositório do GitHub com contém mapas de todo o país por micro, macrorregião e por municípios (https://github.com/tbrugz/geodata-br).

Foi necessária a manipulação do arquivo GEOjson para extrair somente os dados de macrorregião do Ceará. 

o arquivo resultante pode ser visto em: https://github.com/JesseOliveiraUFC/Estudos-de-Casos/blob/main/mapa.json

o resultado obtido é o seguinte mapa: 

![image.png](https://images.zenhubusercontent.com/6231f2fe8cef685d0ca5c6e7/72931149-e31d-46a4-aba3-decb09e7de64)

Após a montagem do mapa, iniciou-se a escrita da nova subsessão do artigo para as macro e microrregiões.

**Comment by JesseOliveiraUFC** [comment]
Progresso de escrita do artigo:

- [x] Introdução
- [x] Metodologia
- [x] Resultados
       - Análise Municipal
       - Análise Regional
       - Comparativo Temporal
- [x] Discussões
- [ ] Conclusão
- [ ] Referências

De acordo com os tópicos acima, podemos caracterizar que cerca de 65% do artigo encontra-se com a escrita concluída.

**Comment by JesseOliveiraUFC** [comment]
Vários avanços significativos na escrita do artigo foram realizados. A sessão de resultados já se encontra quase completa, restando somente a as sessões de discussão e resultados. 

Podemos caracterizar o artigo como 80% concluído.

Segue o artigo para consulta.
[Aqui](https://app.zenhub.com/files/240087549/f3adedb1-d11d-4232-a9a8-9e9ad172506f/download)

Eventuais sugestões são bem-vindas.

**Comment by JesseOliveiraUFC** [comment]
Escrita do artigo avançou para 90%. Foi marcada uma conversa com a Kelma para alinhamento sobre os detalhes finais (conversa foi alinhada na reuniãozona, onde ela se ofereceu para ajudar).

O artigo foi enviado para @Clarisse1983 para revisão.

Segue o arquivo para acesso: [artigo](https://app.zenhub.com/files/240087549/cd09650d-c61d-4504-875b-e78649f3bfef/download)

**Comment by JesseOliveiraUFC** [comment]
O artigo se encontra com 95% da escrita concluída. Após a revisão feita pela @Clarisse1983, muitas de suas contribuições foram acatadas. 

Só falta a escrita do resumo e da conclusão que será feita após conversa com Dr. Sales e/ou Dr. Xavier.

**Comment by vicmagpac** [comment]
Analisar task baseado na desligamento do bolsista Jessé.
